{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-downscaler.keras
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/downscaleR.keras/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2f849dc8b2542e2e20a0c39b7e1ec8b881f0c048f5c70e22f53e3e3a7ec31c1f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-abind
    - r-downscaler >=3.3.2
    - r-keras >=2.2.2
    - r-magrittr
    - r-tensorflow >=2.0.0
    - r-transformer >=2.1.0
  run:
    - r-base
    - r-mass
    - r-abind
    - r-downscaler >=3.3.2
    - r-keras >=2.2.2
    - r-magrittr
    - r-tensorflow >=2.0.0
    - r-transformer >=2.1.0

test:
  commands:
    - $R -e "library('downscaleR.keras')"           # [not win]
    - "\"%R%\" -e \"library('downscaleR.keras')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: Tools for climate downscaling with deep neural networks models building on keras, as part of the climate4R bundle (<http://meteo.unican.es/climate4R>).
  doc_url: https://github.com/SantanderMetGroup/climate4R
  dev_url: https://github.com/SantanderMetGroup/downscaleR.keras
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa


# Package: downscaleR.keras
# Depends: R(>= 3.1.0), transformeR(>= 2.1.0), downscaleR(>= 3.3.2), keras(>= 2.2.2), tensorflow(>= 2.0.0)
# Imports: abind, MASS, utils, stats, magrittr,
# Suggests: loadeR, climate4R.datasets, visualizeR,
# Type: Package
# Title: A climate4R package for statistical downscaling <http://meteo.unican.es/climate4r>
# Version: 1.0.0
# Date: 2021-04-26
# Authors@R: as.person(c( "Santander Meteorology Group <http://meteo.unican.es> [cph]", "Jorge B. Medina <bmedina@ifca.unican.es> [cre]"))
# BugReports: https://github.com/SantanderMetGroup/downscaleR.keras/issues
# URL: http://www.meteo.unican.es/climate4r
# Encoding: UTF-8
# Description: Tools for climate downscaling with deep neural networks models building on keras, as part of the climate4R bundle (<http://meteo.unican.es/climate4R>).
# License: GPL (>= 3)
# LazyData: true
# RoxygenNote: 7.1.0
